from tkinter import *
window=Tk()
window.geometry('600x600')
window.resizable(0,0)
window.title('Calculator')

frame=Frame(window,bg='grey',width=600,height=600,relief='sunken')
frame.grid(column=0,row=0)

entry=Entry(frame,bg='white',relief='sunken')
entry.place(x=20,y=100,relwidth=0.5,relheight=0.5)

btn_a=Button(frame,text='+',bg='sky blue',relief='groove')
btn_a.place(x=20,y=200,relwidth=0.2,relheight=0.1)
btn_m=Button(frame,text='-',bg='sky blue',relief='groove')
btn_m.place(x=20,y=260,relwidth=0.2,relheight=0.1)
btn_d=Button(frame,text='/',bg='sky blue',relief='groove')
btn_d.place(x=20,y=320,relwidth=0.2,relheight=0.1)
btn_mul=Button(frame,text='x',bg='sky blue',relief='groove')
btn_mul.place(x=20,y=380,relwidth=0.2,relheight=0.1)

btn1=Button(frame,text='1',bg='sky blue',relief='groove')
btn1.place(x=130,y=200,relheight=0.1,relwidth=0.1)
btn2=Button(frame,text='2',bg='sky blue',relief='groove')
btn2.place(x=190,y=200,relheight=0.1,relwidth=0.1)
btn3=Button(frame,text='3',bg='sky blue',relief='groove')
btn3.place(x=250,y=200,relheight=0.1,relwidth=0.1)
btn4=Button(frame,text='4',bg='sky blue',relief='groove')
btn4.place(x=310,y=200,relheight=0.1,relwidth=0.1)
btn5=Button(frame,text='5',bg='sky blue',relief='groove')
btn5.place(x=130,y=260,relheight=0.1,relwidth=0.1)
btn6=Button(frame,text='6',bg='sky blue',relief='groove')
btn6.place(x=190,y=260,relheight=0.1,relwidth=0.1)
btn7=Button(frame,text='7',bg='sky blue',relief='groove')
btn7.place(x=250,y=260,relheight=0.1,relwidth=0.1)
btn8=Button(frame,text='8',bg='sky blue',relief='groove')
btn8.place(x=310,y=260,relheight=0.1,relwidth=0.1)
btn9=Button(frame,text='9',bg='sky blue',relief='groove')
btn9.place(x=130,y=320,relheight=0.1,relwidth=0.1)
btn0=Button(frame,text='0',bg='sky blue',relief='groove')
btn0.place(x=190,y=320,relheight=0.1,relwidth=0.1)
btn_p=Button(frame,text='.',bg='sky blue',relief='groove')
btn_p.place(x=250,y=320,relheight=0.1,relwidth=0.1)
btn_eq=Button(frame,text='=',bg='sky blue',relief='groove')
btn_eq.place(x=310,y=320,relheight=0.1,relwidth=0.1)
btn_perc=Button(frame,text='%',bg='sky blue',relief='groove')
btn_perc.place(x=130,y=380,relheight=0.1,relwidth=0.1)
btn_par=Button(frame,text='(',bg='sky blue',relief='groove')
btn_par.place(x=190,y=380,relheight=0.1,relwidth=0.1)
btn_parc=Button(frame,text=')',bg='sky blue',relief='groove')
btn_parc.place(x=250,y=380,relheight=0.1,relwidth=0.1)
btn_C=Button(frame,text='C',bg='sky blue',relief='groove')
btn_C.place(x=310,y=380,relheight=0.1,relwidth=0.1)
window.mainloop()

